# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2020-03-12T20:30:08.379488'

__version__ = '2020.3.4'
__sha__ = '750639b4cf3e32262a90c1f5b98cbe3e9987bab9'
__revision__ = '750639b4cf3e32262a90c1f5b98cbe3e9987bab9'
