# coding: utf-8
from __future__ import absolute_import


# 2 is used by `argparse`.
MAIN_RET_V_PSR_TPLT_EXAMPLE_FILE_CREATE_ERR = 3
MAIN_RET_V_PSR_TPLT_FILE_READ_ERR = 4
MAIN_RET_V_EXT_OPTS_LOAD_ERR = 5
MAIN_RET_V_RULES_FILE_READ_ERR = 6
MAIN_RET_V_TPLT_FILE_READ_ERR = 7
MAIN_RET_V_RULES_PARSE_ERR = 8
MAIN_RET_V_SRC_FILE_READ_ERR = 9
MAIN_RET_V_PSR_CODE_WRITE_FILE_ERR = 10
MAIN_RET_V_PSR_CODE_LOAD_ERR = 11
MAIN_RET_V_PSR_CODE_CALL_ERR = 12
