
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-13T20:04:11+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "321fd81dc8d5e4a2dbd54edc9a196285133f611a",
 "version": "0.10.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
