# Generated by Django 2.2.5 on 2019-09-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='type',
            field=models.CharField(choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('facebook', 'Facebook')], max_length=20, verbose_name='type'),
        ),
    ]
