
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-19T23:10:30+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "626b96db831a05871880cf8d8aa45f351274defc",
 "version": "v0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
