
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-18T23:48:33+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e6572c20ff3dda9a38b7f7f973ff9339ea8c048",
 "version": "v0.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
