# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Map": "tile_generator.ipynb",
         "TileGenerator": "tile_generator.ipynb",
         "create_rectange_polygon": "tile_generator.ipynb",
         "get_quad_grid": "tile_generator.ipynb",
         "generate_train_valid_test": "tile_generator.ipynb"}

modules = ["tile_generator.py"]

doc_url = "https://LU-C4i.github.io/TileGenerator/"

git_url = "https://github.com/LU-C4i/TileGenerator/tree/master/"

def custom_doc_links(name): return None
