
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-10T10:12:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e8d8f400067c5acf09e362cbbfe27c8508b5d60",
 "version": "0.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
