# Generated by Django 2.2.7 on 2019-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Rights',
                'verbose_name_plural': 'Rights',
                'ordering': ['id'],
                'default_permissions': ('add', 'change', 'delete', 'list'),
            },
        ),
    ]
