# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WalletContract(Model):
    """WalletContract.

    :param wallet_id:
    :type wallet_id: str
    :param owner_name:
    :type owner_name: str
    """

    _attribute_map = {
        'wallet_id': {'key': 'walletId', 'type': 'str'},
        'owner_name': {'key': 'ownerName', 'type': 'str'},
    }

    def __init__(self, *, wallet_id: str=None, owner_name: str=None, **kwargs) -> None:
        super(WalletContract, self).__init__(**kwargs)
        self.wallet_id = wallet_id
        self.owner_name = owner_name
