# Generated by Django 2.2.7 on 2019-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Title')),
                ('code', models.TextField(blank=True, editable=False, null=True, verbose_name='Code')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='Category')),
                ('rights_group', models.CharField(blank=True, max_length=64, null=True, verbose_name='Rights group')),
                ('menu', models.CharField(blank=True, max_length=64, null=True, verbose_name='Menu')),
                ('doc', models.TextField(blank=True, editable=False, null=True, verbose_name='Doc')),
                ('_form', models.TextField(blank=True, null=True, verbose_name='_form')),
                ('_view', models.TextField(blank=True, null=True, verbose_name='_view')),
                ('_template', models.TextField(blank=True, null=True, verbose_name='_template')),
            ],
            options={
                'verbose_name': 'Scripts',
                'verbose_name_plural': 'Scripts',
                'ordering': ['id'],
                'default_permissions': ('add', 'change', 'delete', 'list'),
            },
        ),
    ]
