# Generated by Django 3.0.3 on 2020-02-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringtable',
            name='single_char',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='single char'),
        ),
    ]
