# Generated by Django 3.0.3 on 2020-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20200229_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_field', models.IntegerField(blank=True, null=True, verbose_name='int_field')),
                ('dec_field', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='dec_field')),
                ('flt_field', models.FloatField(blank=True, null=True, verbose_name='flt_field')),
            ],
            options={
                'db_table': 'digit',
            },
        ),
    ]
