# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_property',
            name='property_type',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('string', 'String'), ('int', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean')], default=None, max_length=255, null=True),
        ),
    ]
