# Generated by Django 2.2.7 on 2019-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_field', models.BooleanField(default=False, verbose_name='Boolean field')),
                ('char_field', models.CharField(blank=True, max_length=64, null=True, verbose_name='Char field')),
                ('date_field', models.DateField(blank=True, null=True, verbose_name='Data field')),
            ],
            options={
                'verbose_name': 'Grid table',
                'verbose_name_plural': 'Grid table',
                'ordering': ['id'],
                'default_permissions': ('add', 'change', 'delete', 'list'),
            },
        ),
    ]
