
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-08T23:06:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "41c5f2e1f547e860e0c06a50e735dbae2103bbb9",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
