#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['functional_itertools']

package_data = \
{'': ['*']}

install_requires = \
['more-itertools >= 8.2', 'attrs >= 19.3']

extras_require = \
{'dev': ['bump2version >= 1.0', 'pre-commit >= 2.0'],
 'test': ['hypothesis >= 5.5',
          'pytest >= 5.3',
          'pytest-cov >= 2.8',
          'pytest-randomly >= 3.2',
          'pytest-xdist == 1.29']}

setup(name='functional_itertools',
      version='0.5.21',
      description='Python collections in a functional-programming style.',
      author='Bao Wei',
      author_email='baowei.ur521@gmail.com',
      url='https://github.com/baowei521/functional_itertools',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
