# Generated by Django 2.2.2 on 2019-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_prn", "0021_auto_20190516_0000")]

    operations = [
        migrations.AddField(
            model_name="deathreport",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="deathreporttmg",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicaldeathreport",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicaldeathreporttmg",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalprotocoldeviationviolation",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalstudyterminationconclusion",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalstudyterminationconclusionw10",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="protocoldeviationviolation",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="studyterminationconclusion",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="studyterminationconclusionw10",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
    ]
