
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2c0694e802ea5bdb57e8c8252f8a44681208c34f",
 "version": "2266"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
