"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.0.0-beta.117"
COMMIT = "8563644004fc213faeb1de429515e8c7b1c1af36"
MAJOR = 1
MINOR = 0
PATCH = 0
