# Generated by Django 2.2.6 on 2019-10-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ambition_prn", "0039_auto_20191010_0300")]

    operations = [
        migrations.AlterModelOptions(
            name="deathreporttmg",
            options={
                "verbose_name": "Death Report TMG (1st)",
                "verbose_name_plural": "Death Report TMG (1st)",
            },
        ),
        migrations.AlterModelOptions(
            name="deathreporttmgsecond",
            options={
                "verbose_name": "Death Report TMG (2nd)",
                "verbose_name_plural": "Death Report TMG (2nd)",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldeathreporttmg",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Death Report TMG (1st)",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldeathreporttmgsecond",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Death Report TMG (2nd)",
            },
        ),
    ]
