# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    The version of the OpenAPI document: 2020.03.10
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from allegro_api.configuration import Configuration


class GetBadgeCampaignsList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'badge_campaigns': 'list[BadgeCampaign]'
    }

    attribute_map = {
        'badge_campaigns': 'badgeCampaigns'
    }

    def __init__(self, badge_campaigns=None, local_vars_configuration=None):  # noqa: E501
        """GetBadgeCampaignsList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._badge_campaigns = None
        self.discriminator = None

        self.badge_campaigns = badge_campaigns

    @property
    def badge_campaigns(self):
        """Gets the badge_campaigns of this GetBadgeCampaignsList.  # noqa: E501

        List of badge campaigns.  # noqa: E501

        :return: The badge_campaigns of this GetBadgeCampaignsList.  # noqa: E501
        :rtype: list[BadgeCampaign]
        """
        return self._badge_campaigns

    @badge_campaigns.setter
    def badge_campaigns(self, badge_campaigns):
        """Sets the badge_campaigns of this GetBadgeCampaignsList.

        List of badge campaigns.  # noqa: E501

        :param badge_campaigns: The badge_campaigns of this GetBadgeCampaignsList.  # noqa: E501
        :type: list[BadgeCampaign]
        """
        if self.local_vars_configuration.client_side_validation and badge_campaigns is None:  # noqa: E501
            raise ValueError("Invalid value for `badge_campaigns`, must not be `None`")  # noqa: E501

        self._badge_campaigns = badge_campaigns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetBadgeCampaignsList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetBadgeCampaignsList):
            return True

        return self.to_dict() != other.to_dict()
