# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    The version of the OpenAPI document: 2020.03.10
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from allegro_api.configuration import Configuration


class PaymentOperations(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'payment_operations': 'list[BaseOperation]',
        'count': 'int',
        'total_count': 'int'
    }

    attribute_map = {
        'payment_operations': 'paymentOperations',
        'count': 'count',
        'total_count': 'totalCount'
    }

    def __init__(self, payment_operations=None, count=None, total_count=None, local_vars_configuration=None):  # noqa: E501
        """PaymentOperations - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._payment_operations = None
        self._count = None
        self._total_count = None
        self.discriminator = None

        self.payment_operations = payment_operations
        self.count = count
        self.total_count = total_count

    @property
    def payment_operations(self):
        """Gets the payment_operations of this PaymentOperations.  # noqa: E501

        Collection of payment operations.  # noqa: E501

        :return: The payment_operations of this PaymentOperations.  # noqa: E501
        :rtype: list[BaseOperation]
        """
        return self._payment_operations

    @payment_operations.setter
    def payment_operations(self, payment_operations):
        """Sets the payment_operations of this PaymentOperations.

        Collection of payment operations.  # noqa: E501

        :param payment_operations: The payment_operations of this PaymentOperations.  # noqa: E501
        :type: list[BaseOperation]
        """
        if self.local_vars_configuration.client_side_validation and payment_operations is None:  # noqa: E501
            raise ValueError("Invalid value for `payment_operations`, must not be `None`")  # noqa: E501

        self._payment_operations = payment_operations

    @property
    def count(self):
        """Gets the count of this PaymentOperations.  # noqa: E501

        Number of payment operations returned in search result for the given parameters.  # noqa: E501

        :return: The count of this PaymentOperations.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this PaymentOperations.

        Number of payment operations returned in search result for the given parameters.  # noqa: E501

        :param count: The count of this PaymentOperations.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and count is None:  # noqa: E501
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def total_count(self):
        """Gets the total_count of this PaymentOperations.  # noqa: E501

        Total number of payment operations for the given parameters.  # noqa: E501

        :return: The total_count of this PaymentOperations.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this PaymentOperations.

        Total number of payment operations for the given parameters.  # noqa: E501

        :param total_count: The total_count of this PaymentOperations.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and total_count is None:  # noqa: E501
            raise ValueError("Invalid value for `total_count`, must not be `None`")  # noqa: E501

        self._total_count = total_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentOperations):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PaymentOperations):
            return True

        return self.to_dict() != other.to_dict()
