# Generated by Django 2.1.2 on 2018-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail/%Y/%m/%d', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, '显示'), (2, '主菜单'), (0, '隐藏')], default=1, verbose_name='状态'),
        ),
    ]
