# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    The version of the OpenAPI document: 2020.03.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import allegro_api
from allegro_api.models.publication_change_command_dto import PublicationChangeCommandDto  # noqa: E501
from allegro_api.rest import ApiException

class TestPublicationChangeCommandDto(unittest.TestCase):
    """PublicationChangeCommandDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PublicationChangeCommandDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = allegro_api.models.publication_change_command_dto.PublicationChangeCommandDto()  # noqa: E501
        if include_optional :
            return PublicationChangeCommandDto(
                offer_criteria = [
                    allegro_api.models.offer_criterium.OfferCriterium(
                        offers = [
                            allegro_api.models.offer_id.OfferId(
                                id = '0', )
                            ], 
                        type = 'CONTAINS_OFFERS', )
                    ], 
                publication = allegro_api.models.publication_modification.Publication_modification(
                    action = 'ACTIVATE', 
                    scheduled_for = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else :
            return PublicationChangeCommandDto(
        )

    def testPublicationChangeCommandDto(self):
        """Test PublicationChangeCommandDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
