# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    The version of the OpenAPI document: 2020.03.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import allegro_api
from allegro_api.models.offer_listing_dto_v1_stats import OfferListingDtoV1Stats  # noqa: E501
from allegro_api.rest import ApiException

class TestOfferListingDtoV1Stats(unittest.TestCase):
    """OfferListingDtoV1Stats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OfferListingDtoV1Stats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = allegro_api.models.offer_listing_dto_v1_stats.OfferListingDtoV1Stats()  # noqa: E501
        if include_optional :
            return OfferListingDtoV1Stats(
                watchers_count = 99, 
                visits_count = 56
            )
        else :
            return OfferListingDtoV1Stats(
        )

    def testOfferListingDtoV1Stats(self):
        """Test OfferListingDtoV1Stats"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
