# Generated by Django 2.2 on 2019-05-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ambition_prn", "0020_auto_20190505_2311")]

    operations = [
        migrations.RenameField(
            model_name="historicalstudyterminationconclusion",
            old_name="ampho_end_date",
            new_name="ampho_stop_date",
        ),
        migrations.RenameField(
            model_name="studyterminationconclusion",
            old_name="ampho_end_date",
            new_name="ampho_stop_date",
        ),
    ]
