# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mrcEngine.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import common_pb2 as common__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='mrcEngine.proto',
    package='longleding.mrc_engine',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x0fmrcEngine.proto\x12\x15longleding.mrc_engine\x1a\x0c\x63ommon.proto\"@\n\x18OCRResultClassifyRequest\x12\x12\n\nocr_result\x18\x01 \x01(\t\x12\x10\n\x08hospital\x18\x02 \x01(\t\"U\n\x19OCRResultClassifyResponse\x12\x10\n\x08hospital\x18\x01 \x01(\t\x12\x10\n\x08\x64oc_type\x18\x02 \x01(\x05\x12\x14\n\x0csub_doc_type\x18\x03 \x01(\t\"\x8c\x01\n\x18OCRResultMatchingRequest\x12\x12\n\nocr_result\x18\x01 \x01(\t\x12\x10\n\x08hospital\x18\x02 \x01(\t\x12\x10\n\x08\x64oc_type\x18\x03 \x01(\x05\x12\x14\n\x0csub_doc_type\x18\x04 \x01(\t\x12\x0e\n\x06\x66ields\x18\x05 \x03(\t\x12\x12\n\nimage_path\x18\x06 \x01(\t\"\x86\x05\n\x19OCRResultMatchingResponse\x12L\n\x06values\x18\x01 \x03(\x0b\x32<.longleding.mrc_engine.OCRResultMatchingResponse.ValuesEntry\x12L\n\x06\x62ounds\x18\x02 \x03(\x0b\x32<.longleding.mrc_engine.OCRResultMatchingResponse.BoundsEntry\x1a\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x1a\x97\x02\n\x05\x42ound\x12\x42\n\x02p1\x18\x01 \x01(\x0b\x32\x36.longleding.mrc_engine.OCRResultMatchingResponse.Point\x12\x42\n\x02p2\x18\x02 \x01(\x0b\x32\x36.longleding.mrc_engine.OCRResultMatchingResponse.Point\x12\x42\n\x02p3\x18\x03 \x01(\x0b\x32\x36.longleding.mrc_engine.OCRResultMatchingResponse.Point\x12\x42\n\x02p4\x18\x04 \x01(\x0b\x32\x36.longleding.mrc_engine.OCRResultMatchingResponse.Point\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x65\n\x0b\x42oundsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x45\n\x05value\x18\x02 \x01(\x0b\x32\x36.longleding.mrc_engine.OCRResultMatchingResponse.Bound:\x02\x38\x01\x32\xc7\x01\n\tMRCEngine\x12\\\n\x11OCRResultClassify\x12!.longleding.common.RequestMessage\x1a\".longleding.common.ResponseMessage\"\x00\x12\\\n\x11OCRResultMatching\x12!.longleding.common.RequestMessage\x1a\".longleding.common.ResponseMessage\"\x00\x62\x06proto3'
    ,
    dependencies=[common__pb2.DESCRIPTOR, ])

_OCRRESULTCLASSIFYREQUEST = _descriptor.Descriptor(
    name='OCRResultClassifyRequest',
    full_name='longleding.mrc_engine.OCRResultClassifyRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='ocr_result', full_name='longleding.mrc_engine.OCRResultClassifyRequest.ocr_result', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='hospital', full_name='longleding.mrc_engine.OCRResultClassifyRequest.hospital', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=56,
    serialized_end=120,
)

_OCRRESULTCLASSIFYRESPONSE = _descriptor.Descriptor(
    name='OCRResultClassifyResponse',
    full_name='longleding.mrc_engine.OCRResultClassifyResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='hospital', full_name='longleding.mrc_engine.OCRResultClassifyResponse.hospital', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='doc_type', full_name='longleding.mrc_engine.OCRResultClassifyResponse.doc_type', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sub_doc_type', full_name='longleding.mrc_engine.OCRResultClassifyResponse.sub_doc_type', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=122,
    serialized_end=207,
)

_OCRRESULTMATCHINGREQUEST = _descriptor.Descriptor(
    name='OCRResultMatchingRequest',
    full_name='longleding.mrc_engine.OCRResultMatchingRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='ocr_result', full_name='longleding.mrc_engine.OCRResultMatchingRequest.ocr_result', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='hospital', full_name='longleding.mrc_engine.OCRResultMatchingRequest.hospital', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='doc_type', full_name='longleding.mrc_engine.OCRResultMatchingRequest.doc_type', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sub_doc_type', full_name='longleding.mrc_engine.OCRResultMatchingRequest.sub_doc_type', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='fields', full_name='longleding.mrc_engine.OCRResultMatchingRequest.fields', index=4,
            number=5, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='image_path', full_name='longleding.mrc_engine.OCRResultMatchingRequest.image_path', index=5,
            number=6, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=210,
    serialized_end=350,
)

_OCRRESULTMATCHINGRESPONSE_POINT = _descriptor.Descriptor(
    name='Point',
    full_name='longleding.mrc_engine.OCRResultMatchingResponse.Point',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='x', full_name='longleding.mrc_engine.OCRResultMatchingResponse.Point.x', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='y', full_name='longleding.mrc_engine.OCRResultMatchingResponse.Point.y', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=538,
    serialized_end=567,
)

_OCRRESULTMATCHINGRESPONSE_BOUND = _descriptor.Descriptor(
    name='Bound',
    full_name='longleding.mrc_engine.OCRResultMatchingResponse.Bound',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='p1', full_name='longleding.mrc_engine.OCRResultMatchingResponse.Bound.p1', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='p2', full_name='longleding.mrc_engine.OCRResultMatchingResponse.Bound.p2', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='p3', full_name='longleding.mrc_engine.OCRResultMatchingResponse.Bound.p3', index=2,
            number=3, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='p4', full_name='longleding.mrc_engine.OCRResultMatchingResponse.Bound.p4', index=3,
            number=4, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=570,
    serialized_end=849,
)

_OCRRESULTMATCHINGRESPONSE_VALUESENTRY = _descriptor.Descriptor(
    name='ValuesEntry',
    full_name='longleding.mrc_engine.OCRResultMatchingResponse.ValuesEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='longleding.mrc_engine.OCRResultMatchingResponse.ValuesEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='longleding.mrc_engine.OCRResultMatchingResponse.ValuesEntry.value', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=b'8\001',
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=851,
    serialized_end=896,
)

_OCRRESULTMATCHINGRESPONSE_BOUNDSENTRY = _descriptor.Descriptor(
    name='BoundsEntry',
    full_name='longleding.mrc_engine.OCRResultMatchingResponse.BoundsEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='longleding.mrc_engine.OCRResultMatchingResponse.BoundsEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='longleding.mrc_engine.OCRResultMatchingResponse.BoundsEntry.value', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=b'8\001',
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=898,
    serialized_end=999,
)

_OCRRESULTMATCHINGRESPONSE = _descriptor.Descriptor(
    name='OCRResultMatchingResponse',
    full_name='longleding.mrc_engine.OCRResultMatchingResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='values', full_name='longleding.mrc_engine.OCRResultMatchingResponse.values', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='bounds', full_name='longleding.mrc_engine.OCRResultMatchingResponse.bounds', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_OCRRESULTMATCHINGRESPONSE_POINT, _OCRRESULTMATCHINGRESPONSE_BOUND, _OCRRESULTMATCHINGRESPONSE_VALUESENTRY, _OCRRESULTMATCHINGRESPONSE_BOUNDSENTRY, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=353,
    serialized_end=999,
)

_OCRRESULTMATCHINGRESPONSE_POINT.containing_type = _OCRRESULTMATCHINGRESPONSE
_OCRRESULTMATCHINGRESPONSE_BOUND.fields_by_name['p1'].message_type = _OCRRESULTMATCHINGRESPONSE_POINT
_OCRRESULTMATCHINGRESPONSE_BOUND.fields_by_name['p2'].message_type = _OCRRESULTMATCHINGRESPONSE_POINT
_OCRRESULTMATCHINGRESPONSE_BOUND.fields_by_name['p3'].message_type = _OCRRESULTMATCHINGRESPONSE_POINT
_OCRRESULTMATCHINGRESPONSE_BOUND.fields_by_name['p4'].message_type = _OCRRESULTMATCHINGRESPONSE_POINT
_OCRRESULTMATCHINGRESPONSE_BOUND.containing_type = _OCRRESULTMATCHINGRESPONSE
_OCRRESULTMATCHINGRESPONSE_VALUESENTRY.containing_type = _OCRRESULTMATCHINGRESPONSE
_OCRRESULTMATCHINGRESPONSE_BOUNDSENTRY.fields_by_name['value'].message_type = _OCRRESULTMATCHINGRESPONSE_BOUND
_OCRRESULTMATCHINGRESPONSE_BOUNDSENTRY.containing_type = _OCRRESULTMATCHINGRESPONSE
_OCRRESULTMATCHINGRESPONSE.fields_by_name['values'].message_type = _OCRRESULTMATCHINGRESPONSE_VALUESENTRY
_OCRRESULTMATCHINGRESPONSE.fields_by_name['bounds'].message_type = _OCRRESULTMATCHINGRESPONSE_BOUNDSENTRY
DESCRIPTOR.message_types_by_name['OCRResultClassifyRequest'] = _OCRRESULTCLASSIFYREQUEST
DESCRIPTOR.message_types_by_name['OCRResultClassifyResponse'] = _OCRRESULTCLASSIFYRESPONSE
DESCRIPTOR.message_types_by_name['OCRResultMatchingRequest'] = _OCRRESULTMATCHINGREQUEST
DESCRIPTOR.message_types_by_name['OCRResultMatchingResponse'] = _OCRRESULTMATCHINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OCRResultClassifyRequest = _reflection.GeneratedProtocolMessageType('OCRResultClassifyRequest', (_message.Message,), {
    'DESCRIPTOR': _OCRRESULTCLASSIFYREQUEST,
    '__module__': 'mrcEngine_pb2'
    # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultClassifyRequest)
})
_sym_db.RegisterMessage(OCRResultClassifyRequest)

OCRResultClassifyResponse = _reflection.GeneratedProtocolMessageType('OCRResultClassifyResponse', (_message.Message,), {
    'DESCRIPTOR': _OCRRESULTCLASSIFYRESPONSE,
    '__module__': 'mrcEngine_pb2'
    # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultClassifyResponse)
})
_sym_db.RegisterMessage(OCRResultClassifyResponse)

OCRResultMatchingRequest = _reflection.GeneratedProtocolMessageType('OCRResultMatchingRequest', (_message.Message,), {
    'DESCRIPTOR': _OCRRESULTMATCHINGREQUEST,
    '__module__': 'mrcEngine_pb2'
    # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultMatchingRequest)
})
_sym_db.RegisterMessage(OCRResultMatchingRequest)

OCRResultMatchingResponse = _reflection.GeneratedProtocolMessageType('OCRResultMatchingResponse', (_message.Message,), {

    'Point': _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
        'DESCRIPTOR': _OCRRESULTMATCHINGRESPONSE_POINT,
        '__module__': 'mrcEngine_pb2'
        # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultMatchingResponse.Point)
    })
    ,

    'Bound': _reflection.GeneratedProtocolMessageType('Bound', (_message.Message,), {
        'DESCRIPTOR': _OCRRESULTMATCHINGRESPONSE_BOUND,
        '__module__': 'mrcEngine_pb2'
        # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultMatchingResponse.Bound)
    })
    ,

    'ValuesEntry': _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), {
        'DESCRIPTOR': _OCRRESULTMATCHINGRESPONSE_VALUESENTRY,
        '__module__': 'mrcEngine_pb2'
        # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultMatchingResponse.ValuesEntry)
    })
    ,

    'BoundsEntry': _reflection.GeneratedProtocolMessageType('BoundsEntry', (_message.Message,), {
        'DESCRIPTOR': _OCRRESULTMATCHINGRESPONSE_BOUNDSENTRY,
        '__module__': 'mrcEngine_pb2'
        # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultMatchingResponse.BoundsEntry)
    })
    ,
    'DESCRIPTOR': _OCRRESULTMATCHINGRESPONSE,
    '__module__': 'mrcEngine_pb2'
    # @@protoc_insertion_point(class_scope:longleding.mrc_engine.OCRResultMatchingResponse)
})
_sym_db.RegisterMessage(OCRResultMatchingResponse)
_sym_db.RegisterMessage(OCRResultMatchingResponse.Point)
_sym_db.RegisterMessage(OCRResultMatchingResponse.Bound)
_sym_db.RegisterMessage(OCRResultMatchingResponse.ValuesEntry)
_sym_db.RegisterMessage(OCRResultMatchingResponse.BoundsEntry)

_OCRRESULTMATCHINGRESPONSE_VALUESENTRY._options = None
_OCRRESULTMATCHINGRESPONSE_BOUNDSENTRY._options = None

_MRCENGINE = _descriptor.ServiceDescriptor(
    name='MRCEngine',
    full_name='longleding.mrc_engine.MRCEngine',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=1002,
    serialized_end=1201,
    methods=[
        _descriptor.MethodDescriptor(
            name='OCRResultClassify',
            full_name='longleding.mrc_engine.MRCEngine.OCRResultClassify',
            index=0,
            containing_service=None,
            input_type=common__pb2._REQUESTMESSAGE,
            output_type=common__pb2._RESPONSEMESSAGE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='OCRResultMatching',
            full_name='longleding.mrc_engine.MRCEngine.OCRResultMatching',
            index=1,
            containing_service=None,
            input_type=common__pb2._REQUESTMESSAGE,
            output_type=common__pb2._RESPONSEMESSAGE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_MRCENGINE)

DESCRIPTOR.services_by_name['MRCEngine'] = _MRCENGINE

# @@protoc_insertion_point(module_scope)
