# Generated by Django 3.0.2 on 2020-01-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
