# Generated by Django 2.2.11 on 2020-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_model_admin', '0002_modelfield_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Datas'},
        ),
        migrations.AlterModelOptions(
            name='fieldwidget',
            options={'verbose_name': 'Field Widget', 'verbose_name_plural': 'Field Widgets'},
        ),
        migrations.AlterModelOptions(
            name='modeldefinition',
            options={'verbose_name': 'Model Definition', 'verbose_name_plural': 'Model Definitions'},
        ),
        migrations.AlterModelOptions(
            name='modeldefinitioncategory',
            options={'verbose_name': 'Model Definition Category', 'verbose_name_plural': 'Model Definition Categories'},
        ),
        migrations.AlterModelOptions(
            name='modelfield',
            options={'verbose_name': 'Model Field', 'verbose_name_plural': 'Model Fields'},
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='label_width',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='Label Width'),
        ),
    ]
