# Generated by Django 2.2.11 on 2020-03-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_model_admin', '0003_auto_20200313_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldefinition',
            name='fieldsets_data',
        ),
    ]
