# Generated by Django 2.2.11 on 2020-03-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_model_admin', '0009_modelinline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='is_draft',
        ),
    ]
