# Generated by Django 2.2.11 on 2020-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_model_admin', '0010_remove_data_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinline',
            name='extra',
            field=models.IntegerField(default=0, verbose_name='Extra Data Number'),
        ),
        migrations.AddField(
            model_name='modelinline',
            name='type',
            field=models.IntegerField(choices=[(1, 'TabularInline'), (2, 'StackedInline')], default=1, verbose_name='Inline Type'),
        ),
    ]
