# Generated by Django 2.2.11 on 2020-03-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_model_admin', '0011_auto_20200314_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelinline',
            options={'ordering': ['order'], 'verbose_name': 'Model Inline', 'verbose_name_plural': 'Model Inlines'},
        ),
        migrations.AddField(
            model_name='modelinline',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
