
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-10T08:54:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7e07dc97d6f4233c76078fd7a9be26db006b22a",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
