# Generated by Django 2.2.7 on 2019-11-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambition_lists", "0008_auto_20191108_0752"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="abnormalresultsreason",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_ae30e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="antibiotic",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_bb8ce2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arvregimens",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_c4bf1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cxrtype",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_4634e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="day14medication",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_3adc0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="infiltratelocation",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_5058d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_dd8905_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="misseddoses",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_629dbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="neurological",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_5dce1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otherdrug",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_2e681e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="significantnewdiagnosis",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_cb2a00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="symptom",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_su_id_a1d341_idx",
            ),
        ),
    ]
