
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-06T15:53:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "01dbc0fe408c3c8025164d9b8345250aea69de32",
 "version": "0.3.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
