# Generated by Django 2.1.2 on 2018-11-08 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("ambition_ae", "0016_auto_20181031_0628")]

    operations = [
        migrations.AlterField(
            model_name="historicalaefollowup",
            name="history_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="history_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalaetmg",
            name="history_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecurrencesymptom",
            name="history_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
