# Generated by Django 2.2.2 on 2019-08-01 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edc_adverse_event", "0001_initial"),
        ("ambition_ae", "0028_auto_20190628_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="aeinitial",
            name="ae_classification_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_adverse_event.AeClassification",
            ),
        ),
        migrations.AddField(
            model_name="historicalaeinitial",
            name="ae_classification_new",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_adverse_event.AeClassification",
            ),
        ),
        migrations.AlterField(
            model_name="aeinitial",
            name="ae_classification",
            field=models.CharField(
                choices=[
                    ("anaemia", "Anaemia"),
                    ("bacteraemia/sepsis", "Bacteraemia/Sepsis"),
                    ("CM_IRIS", "CM IRIS"),
                    ("diarrhoea", "Diarrhoea"),
                    ("hypokalaemia", "Hypokalaemia"),
                    ("neutropaenia", "Neutropaenia"),
                    ("pneumonia", "Pneumonia"),
                    ("renal_impairment", "Renal impairment"),
                    ("respiratory_distress", "Respiratory distress"),
                    ("TB", "TB"),
                    ("thrombocytopenia", "Thrombocytopenia"),
                    ("thrombophlebitis", "Thrombophlebitis"),
                    ("OTHER", "Other"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="ae_classification",
            field=models.CharField(
                choices=[
                    ("anaemia", "Anaemia"),
                    ("bacteraemia/sepsis", "Bacteraemia/Sepsis"),
                    ("CM_IRIS", "CM IRIS"),
                    ("diarrhoea", "Diarrhoea"),
                    ("hypokalaemia", "Hypokalaemia"),
                    ("neutropaenia", "Neutropaenia"),
                    ("pneumonia", "Pneumonia"),
                    ("renal_impairment", "Renal impairment"),
                    ("respiratory_distress", "Respiratory distress"),
                    ("TB", "TB"),
                    ("thrombocytopenia", "Thrombocytopenia"),
                    ("thrombophlebitis", "Thrombophlebitis"),
                    ("OTHER", "Other"),
                ],
                max_length=150,
            ),
        ),
    ]
