# Generated by Django 2.2 on 2019-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0003_pbsmmspecial_show_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmmspecial',
            name='show_api_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Show Object ID'),
        ),
    ]
