
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-08T13:00:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd13f2bfbb3ddb6c626b5b0c69326fcee5904e00",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
