# Generated by Django 2.2 on 2019-05-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0048_auto_20190516_0000")]

    operations = [
        migrations.AlterField(
            model_name="bloodresult",
            name="wbc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="WBC",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbloodresult",
            name="wbc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="WBC",
            ),
        ),
    ]
