# Generated by Django 2.2 on 2019-05-29 07:18

from django.db import migrations


def remove_azt(apps, schema_editor):
    ArvRegimens = apps.get_model("ambition_lists", "arvregimens")
    ArvRegimens.objects.filter(name="AZT_r").delete()


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0057_auto_20190523_0552")]

    operations = [migrations.RunPython(remove_azt)]
