# Generated by Django 2.2.2 on 2019-06-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0060_auto_20190627_2257")]

    operations = [
        migrations.AddIndex(
            model_name="subjectconsent",
            index=models.Index(
                fields=[
                    "subject_identifier",
                    "first_name",
                    "dob",
                    "initials",
                    "version",
                ],
                name="ambition_su_subject_00a72d_idx",
            ),
        )
    ]
