# Generated by Django 2.2.2 on 2019-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0061_auto_20190627_2306")]

    operations = [
        migrations.AddIndex(
            model_name="bloodresult",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_3255ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="education",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_a5ddb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="educationhoh",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_7e2ada_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_63c674_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lumbarpuncturecsf",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_af0813_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalexpenses",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_3818cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalexpensestwo",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_422a28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="microbiology",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_da7828_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patienthistory",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_57056b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pkpdcrf",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_8c372e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiology",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_3f9f8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="week16",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_7e1899_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="week2",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_d0f90d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="week4",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="ambition_su_subject_73cd0d_idx",
            ),
        ),
    ]
