# Generated by Django 2.2 on 2019-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_auto_20190430_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmmepisode',
            name='season_api_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Season Object ID'),
        ),
    ]
