
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-13T10:34:46+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfc23015b51fa669c681c264c5c60ae4505f0895",
 "version": "v0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
