
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-18T09:59:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "32d720129b2d75a686bc129f52bd0be70a3147dd",
 "version": "1.3.3.post.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
