# -*- generated by 1.0.14 -*-
import da
PatternExpr_244 = da.pat.TuplePattern([da.pat.ConstantPattern('access'), da.pat.FreePattern('newtok')])
PatternExpr_256 = da.pat.TuplePattern([da.pat.ConstantPattern('request'), da.pat.FreePattern('c'), da.pat.FreePattern('p')])
PatternExpr_284 = da.pat.TuplePattern([da.pat.ConstantPattern('request'), da.pat.FreePattern('c'), da.pat.BoundPattern('_BoundPattern289_')])
PatternExpr_319 = da.pat.TuplePattern([da.pat.ConstantPattern('access'), da.pat.FreePattern(None)])
PatternExpr_340 = da.pat.TuplePattern([da.pat.ConstantPattern('access'), da.pat.FreePattern('token1')])
PatternExpr_362 = da.pat.TuplePattern([da.pat.ConstantPattern('access'), da.pat.FreePattern('token2')])
PatternExpr_425 = da.pat.TuplePattern([da.pat.ConstantPattern('Done')])
PatternExpr_430 = da.pat.BoundPattern('_BoundPattern431_')
PatternExpr_432 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.BoundPattern('_BoundPattern438_')]), da.pat.TuplePattern([da.pat.ConstantPattern('Done')])])
_config_object = {}
import sys

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._PReceivedEvent_2 = []
        self._PSentEvent_3 = []
        self._PReceivedEvent_4 = []
        self._PSentEvent_5 = []
        self._PReceivedEvent_6 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_0', PatternExpr_244, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_243]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_1', PatternExpr_256, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_255]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_2', PatternExpr_284, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.SentEvent, '_PSentEvent_3', PatternExpr_319, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_4', PatternExpr_340, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.SentEvent, '_PSentEvent_5', PatternExpr_362, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_6', PatternExpr_425, sources=[PatternExpr_430], destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, ps, nrounds, orig_token, **rest_520):
        super().setup(ps=ps, nrounds=nrounds, orig_token=orig_token, **rest_520)
        self._state.ps = ps
        self._state.nrounds = nrounds
        self._state.orig_token = orig_token
        self._state.clock = 0
        self._state.token = dict(((p, 0) for p in self._state.ps))

    def run(self):

        def anounce():
            self.output('In cs!')
        if self.token_present():
            self.output("I'm lucky!")
        for i in range(self._state.nrounds):
            self.cs(anounce)
        self.send(('Done',), to=self._state.ps)
        super()._label('_st_label_416', block=False)
        p = None

        def UniversalOpExpr_417():
            nonlocal p
            for p in self._state.ps:
                if (not PatternExpr_432.match_iter(self._PReceivedEvent_6, _BoundPattern438_=p, SELF_ID=self._id)):
                    return False
            return True
        _st_label_416 = 0
        while (_st_label_416 == 0):
            _st_label_416 += 1
            if UniversalOpExpr_417():
                _st_label_416 += 1
            else:
                super()._label('_st_label_416', block=True)
                _st_label_416 -= 1
        self.output('Done!')

    def cs(self, task):
        super()._label('request', block=False)
        if (not self.token_present()):
            self._state.clock += 1
            self.send(('request', self._state.clock, self._id), to=self._state.ps)
            super()._label('_st_label_211', block=False)
            _st_label_211 = 0
            while (_st_label_211 == 0):
                _st_label_211 += 1
                if self.token_present():
                    _st_label_211 += 1
                else:
                    super()._label('_st_label_211', block=True)
                    _st_label_211 -= 1
        self._state.token[self._id] = self._state.clock
        task()
        super()._label('release', block=False)
        for p in self._state.ps:
            if (self.request_pending(p) and self.token_present()):
                self.send(('access', self._state.token), to=p)
                break

    def request_pending(self, p):
        c = None

        def ExistentialOpExpr_282():
            nonlocal c
            for (_, _, (_ConstantPattern300_, c, _BoundPattern303_)) in self._PReceivedEvent_2:
                if (_ConstantPattern300_ == 'request'):
                    if (_BoundPattern303_ == p):
                        if (c > self._state.token[p]):
                            return True
            return False
        return ExistentialOpExpr_282()

    def token_present(self):

        def ExistentialOpExpr_317():
            for (_, _, (_ConstantPattern333_, _)) in self._PSentEvent_3:
                if (_ConstantPattern333_ == 'access'):
                    if True:
                        return True
            return False
        token2 = token1 = None

        def ExistentialOpExpr_338():
            nonlocal token2, token1
            for (_, _, (_ConstantPattern355_, token1)) in self._PReceivedEvent_4:
                if (_ConstantPattern355_ == 'access'):

                    def ExistentialOpExpr_360(token1):
                        nonlocal token2
                        for (_, _, (_ConstantPattern377_, token2)) in self._PSentEvent_5:
                            if (_ConstantPattern377_ == 'access'):
                                if (token2[self._id] > token1[self._id]):
                                    return True
                        return False
                    if (not ExistentialOpExpr_360(token1=token1)):
                        return True
            return False
        return ((self._state.orig_token and (not ExistentialOpExpr_317())) or ExistentialOpExpr_338())

    def _P_handler_243(self, newtok):
        self._state.token = newtok
    _P_handler_243._labels = None
    _P_handler_243._notlabels = None

    def _P_handler_255(self, c, p):
        if (self.request_pending(p) and self.token_present()):
            self.send(('access', self._state.token), to=p)
    _P_handler_255._labels = None
    _P_handler_255._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        nprocs = (int(sys.argv[1]) if (len(sys.argv) > 1) else 10)
        nrounds = (int(sys.argv[2]) if (len(sys.argv) > 2) else 1)
        ps = self.new(P, num=nprocs)
        p = ps.pop()
        self._setup(ps, ((ps | {p}), nrounds, False))
        self._setup([p], ((ps | {p}), nrounds, True))
        self._start((ps | {p}))
