
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-08T21:39:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e25f11be3e0fc8dc4422492f391d60c2a32dc1a2",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
