# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diff.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Diff(object):
    def setupUi(self, Diff):
        Diff.setObjectName("Diff")
        Diff.resize(800, 539)
        Diff.setAutoFillBackground(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Diff)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Diff)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(646, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.highlightButton = QtWidgets.QPushButton(self.widget)
        self.highlightButton.setMinimumSize(QtCore.QSize(120, 0))
        self.highlightButton.setCheckable(True)
        self.highlightButton.setObjectName("highlightButton")
        self.horizontalLayout.addWidget(self.highlightButton)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.referenceScrollArea = QtWidgets.QScrollArea(Diff)
        self.referenceScrollArea.setWidgetResizable(True)
        self.referenceScrollArea.setObjectName("referenceScrollArea")
        self.referenceScrollAreaContents = QtWidgets.QWidget()
        self.referenceScrollAreaContents.setGeometry(QtCore.QRect(0, 0, 385, 463))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.referenceScrollAreaContents.setPalette(palette)
        self.referenceScrollAreaContents.setObjectName("referenceScrollAreaContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.referenceScrollAreaContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.referenceImageLabel = QtWidgets.QLabel(self.referenceScrollAreaContents)
        self.referenceImageLabel.setText("")
        self.referenceImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.referenceImageLabel.setObjectName("referenceImageLabel")
        self.horizontalLayout_2.addWidget(self.referenceImageLabel)
        self.referenceScrollArea.setWidget(self.referenceScrollAreaContents)
        self.horizontalLayout_4.addWidget(self.referenceScrollArea)
        self.resultScrollArea = QtWidgets.QScrollArea(Diff)
        self.resultScrollArea.setWidgetResizable(True)
        self.resultScrollArea.setObjectName("resultScrollArea")
        self.resultScrollAreaContents = QtWidgets.QWidget()
        self.resultScrollAreaContents.setGeometry(QtCore.QRect(0, 0, 385, 463))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.resultScrollAreaContents.setPalette(palette)
        self.resultScrollAreaContents.setObjectName("resultScrollAreaContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.resultScrollAreaContents)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resultImageLabel = QtWidgets.QLabel(self.resultScrollAreaContents)
        self.resultImageLabel.setText("")
        self.resultImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultImageLabel.setObjectName("resultImageLabel")
        self.horizontalLayout_3.addWidget(self.resultImageLabel)
        self.resultScrollArea.setWidget(self.resultScrollAreaContents)
        self.horizontalLayout_4.addWidget(self.resultScrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(Diff)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Diff)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Diff)
        self.highlightButton.released.connect(Diff.swap_results)
        self.pushButton.released.connect(Diff.save_images)
        QtCore.QMetaObject.connectSlotsByName(Diff)

    def retranslateUi(self, Diff):
        _translate = QtCore.QCoreApplication.translate
        Diff.setWindowTitle(_translate("Diff", "Screenshot comparison"))
        self.highlightButton.setText(_translate("Diff", "Highlight differences"))
        self.pushButton.setText(_translate("Diff", "Export as image…"))
        self.label.setText(_translate("Diff", "Reference"))
        self.label_2.setText(_translate("Diff", "Test result"))
