# Generated by Django 2.0.3 on 2018-04-09 10:13

import ambition_subject.managers
import ambition_subject.models.subject_visit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0007_auto_20180227_1004")]

    operations = [
        migrations.AlterModelManagers(
            name="bloodresult",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="education",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="educationhoh",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="followup",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="lumbarpuncturecsf",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="medicalexpenses",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="medicalexpensestwo",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="microbiology",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="patienthistory",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="pkpdcrf",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="radiology",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="subjectconsent",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="subjectreconsent",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="subjectrequisition",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="subjectvisit",
            managers=[
                ("on_site", ambition_subject.models.subject_visit.CurrentSiteManager())
            ],
        ),
        migrations.AlterModelManagers(
            name="week16",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="week2",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AlterModelManagers(
            name="week4",
            managers=[("on_site", ambition_subject.managers.CurrentSiteManager())],
        ),
        migrations.AddField(
            model_name="bloodresult",
            name="parent_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="bloodresult",
            name="related_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresult",
            name="parent_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresult",
            name="related_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalsubjectreconsent",
            name="parent_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalsubjectreconsent",
            name="related_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="subjectreconsent",
            name="parent_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="subjectreconsent",
            name="related_tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="bloodresult",
            name="tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbloodresult",
            name="tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsubjectreconsent",
            name="tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="subjectreconsent",
            name="tracking_identifier",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
