# Generated by Django 2.2.7 on 2019-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autocomplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('label', models.CharField(max_length=64, verbose_name='Label')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Autocomplete',
                'verbose_name_plural': 'Autocomplete',
                'ordering': ['id'],
                'default_permissions': ('add', 'change', 'delete', 'list'),
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=16, null=True, verbose_name='Parameter type')),
                ('subtype', models.CharField(blank=True, max_length=16, null=True, verbose_name='Parameter subtype')),
                ('key', models.CharField(max_length=64, verbose_name='Key')),
                ('value', models.CharField(max_length=64, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameter',
                'ordering': ['id'],
                'default_permissions': ('add', 'change', 'delete', 'list'),
            },
        ),
    ]
