# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/compiler/xla/python/tpu_driver/tpu_driver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow/compiler/xla/python/tpu_driver/tpu_driver.proto',
  package='tpu_driver',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n:tensorflow/compiler/xla/python/tpu_driver/tpu_driver.proto\x12\ntpu_driver\"U\n\x0bTpuCoreInfo\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x1b\n\x13hbm_bytes_available\x18\x64 \x02(\x03\x12\x1d\n\x15hbm_bytes_allocatable\x18\x65 \x02(\x03\"4\n\x0bTpuChipInfo\x12%\n\x04\x63ore\x18\x01 \x03(\x0b\x32\x17.tpu_driver.TpuCoreInfo\"u\n\x07\x43puInfo\x12\x15\n\rnum_cpu_cores\x18\x01 \x02(\x05\x12\x1d\n\x15\x63pu_load_average_1min\x18\x02 \x02(\x02\x12\x17\n\x0fram_bytes_total\x18\x64 \x02(\x03\x12\x1b\n\x13ram_bytes_available\x18\x65 \x02(\x03\"Y\n\nSystemInfo\x12)\n\x08tpu_chip\x18\x01 \x03(\x0b\x32\x17.tpu_driver.TpuChipInfo\x12 \n\x03\x63pu\x18\x02 \x02(\x0b\x32\x13.tpu_driver.CpuInfo\"\xae\x01\n\x0fTpuDriverConfig\x12\x0e\n\x06worker\x18\x01 \x01(\t\x12\x34\n\x04grpc\x18\x02 \x01(\x0b\x32&.tpu_driver.TpuDriverConfig.GrpcConfig\x1aU\n\nGrpcConfig\x12#\n\x17\x63onnection_timeout_secs\x18\x01 \x01(\x03:\x02\x33\x30\x12\"\n\x16keepalive_timeout_secs\x18\x02 \x01(\x03:\x02\x33\x30*\x17\n\x0cMemoryRegion\x12\x07\n\x03HBM\x10\x01')
)

_MEMORYREGION = _descriptor.EnumDescriptor(
  name='MemoryRegion',
  full_name='tpu_driver.MemoryRegion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HBM', index=0, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=602,
  serialized_end=625,
)
_sym_db.RegisterEnumDescriptor(_MEMORYREGION)

MemoryRegion = enum_type_wrapper.EnumTypeWrapper(_MEMORYREGION)
HBM = 1



_TPUCOREINFO = _descriptor.Descriptor(
  name='TpuCoreInfo',
  full_name='tpu_driver.TpuCoreInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tpu_driver.TpuCoreInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hbm_bytes_available', full_name='tpu_driver.TpuCoreInfo.hbm_bytes_available', index=1,
      number=100, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hbm_bytes_allocatable', full_name='tpu_driver.TpuCoreInfo.hbm_bytes_allocatable', index=2,
      number=101, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=159,
)


_TPUCHIPINFO = _descriptor.Descriptor(
  name='TpuChipInfo',
  full_name='tpu_driver.TpuChipInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='core', full_name='tpu_driver.TpuChipInfo.core', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=213,
)


_CPUINFO = _descriptor.Descriptor(
  name='CpuInfo',
  full_name='tpu_driver.CpuInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_cpu_cores', full_name='tpu_driver.CpuInfo.num_cpu_cores', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_load_average_1min', full_name='tpu_driver.CpuInfo.cpu_load_average_1min', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ram_bytes_total', full_name='tpu_driver.CpuInfo.ram_bytes_total', index=2,
      number=100, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ram_bytes_available', full_name='tpu_driver.CpuInfo.ram_bytes_available', index=3,
      number=101, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=332,
)


_SYSTEMINFO = _descriptor.Descriptor(
  name='SystemInfo',
  full_name='tpu_driver.SystemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tpu_chip', full_name='tpu_driver.SystemInfo.tpu_chip', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu', full_name='tpu_driver.SystemInfo.cpu', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=423,
)


_TPUDRIVERCONFIG_GRPCCONFIG = _descriptor.Descriptor(
  name='GrpcConfig',
  full_name='tpu_driver.TpuDriverConfig.GrpcConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection_timeout_secs', full_name='tpu_driver.TpuDriverConfig.GrpcConfig.connection_timeout_secs', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=30,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keepalive_timeout_secs', full_name='tpu_driver.TpuDriverConfig.GrpcConfig.keepalive_timeout_secs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=30,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=600,
)

_TPUDRIVERCONFIG = _descriptor.Descriptor(
  name='TpuDriverConfig',
  full_name='tpu_driver.TpuDriverConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker', full_name='tpu_driver.TpuDriverConfig.worker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grpc', full_name='tpu_driver.TpuDriverConfig.grpc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TPUDRIVERCONFIG_GRPCCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=600,
)

_TPUCHIPINFO.fields_by_name['core'].message_type = _TPUCOREINFO
_SYSTEMINFO.fields_by_name['tpu_chip'].message_type = _TPUCHIPINFO
_SYSTEMINFO.fields_by_name['cpu'].message_type = _CPUINFO
_TPUDRIVERCONFIG_GRPCCONFIG.containing_type = _TPUDRIVERCONFIG
_TPUDRIVERCONFIG.fields_by_name['grpc'].message_type = _TPUDRIVERCONFIG_GRPCCONFIG
DESCRIPTOR.message_types_by_name['TpuCoreInfo'] = _TPUCOREINFO
DESCRIPTOR.message_types_by_name['TpuChipInfo'] = _TPUCHIPINFO
DESCRIPTOR.message_types_by_name['CpuInfo'] = _CPUINFO
DESCRIPTOR.message_types_by_name['SystemInfo'] = _SYSTEMINFO
DESCRIPTOR.message_types_by_name['TpuDriverConfig'] = _TPUDRIVERCONFIG
DESCRIPTOR.enum_types_by_name['MemoryRegion'] = _MEMORYREGION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TpuCoreInfo = _reflection.GeneratedProtocolMessageType('TpuCoreInfo', (_message.Message,), dict(
  DESCRIPTOR = _TPUCOREINFO,
  __module__ = 'tensorflow.compiler.xla.python.tpu_driver.tpu_driver_pb2'
  # @@protoc_insertion_point(class_scope:tpu_driver.TpuCoreInfo)
  ))
_sym_db.RegisterMessage(TpuCoreInfo)

TpuChipInfo = _reflection.GeneratedProtocolMessageType('TpuChipInfo', (_message.Message,), dict(
  DESCRIPTOR = _TPUCHIPINFO,
  __module__ = 'tensorflow.compiler.xla.python.tpu_driver.tpu_driver_pb2'
  # @@protoc_insertion_point(class_scope:tpu_driver.TpuChipInfo)
  ))
_sym_db.RegisterMessage(TpuChipInfo)

CpuInfo = _reflection.GeneratedProtocolMessageType('CpuInfo', (_message.Message,), dict(
  DESCRIPTOR = _CPUINFO,
  __module__ = 'tensorflow.compiler.xla.python.tpu_driver.tpu_driver_pb2'
  # @@protoc_insertion_point(class_scope:tpu_driver.CpuInfo)
  ))
_sym_db.RegisterMessage(CpuInfo)

SystemInfo = _reflection.GeneratedProtocolMessageType('SystemInfo', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMINFO,
  __module__ = 'tensorflow.compiler.xla.python.tpu_driver.tpu_driver_pb2'
  # @@protoc_insertion_point(class_scope:tpu_driver.SystemInfo)
  ))
_sym_db.RegisterMessage(SystemInfo)

TpuDriverConfig = _reflection.GeneratedProtocolMessageType('TpuDriverConfig', (_message.Message,), dict(

  GrpcConfig = _reflection.GeneratedProtocolMessageType('GrpcConfig', (_message.Message,), dict(
    DESCRIPTOR = _TPUDRIVERCONFIG_GRPCCONFIG,
    __module__ = 'tensorflow.compiler.xla.python.tpu_driver.tpu_driver_pb2'
    # @@protoc_insertion_point(class_scope:tpu_driver.TpuDriverConfig.GrpcConfig)
    ))
  ,
  DESCRIPTOR = _TPUDRIVERCONFIG,
  __module__ = 'tensorflow.compiler.xla.python.tpu_driver.tpu_driver_pb2'
  # @@protoc_insertion_point(class_scope:tpu_driver.TpuDriverConfig)
  ))
_sym_db.RegisterMessage(TpuDriverConfig)
_sym_db.RegisterMessage(TpuDriverConfig.GrpcConfig)


# @@protoc_insertion_point(module_scope)
