
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-03-11T16:28:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "31eb2dc5aea3607e6324bd8ebbfeea3730eeaa10",
 "version": "0.7.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
