
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-16T05:36:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6927b20b638d21c7684de775357e8c02529b1871",
 "version": "0.3.3.post.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
