# Generated by Django 2.2.5 on 2019-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_prn", "0033_auto_20190820_0030")]

    operations = [
        migrations.AlterField(
            model_name="historicalonschedule",
            name="subject_identifier",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalonschedulew10",
            name="subject_identifier",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="onschedule",
            name="subject_identifier",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="onschedulew10",
            name="subject_identifier",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
