# Generated by Django 2.1.2 on 2019-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20181023_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近登陆'),
        ),
    ]
