
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9abf6807684066712478ca5d2ab55c2ddd1da92e",
 "version": "2273"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
