
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-18T15:13:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "534da73a15d90fb6a05c4dd0d65c675520f4acc9",
 "version": "1.0.0.alpha.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
