# Generated by Django 2.2 on 2020-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosubscribe', '0002_auto_20200318_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribermodel',
            name='email',
            field=models.EmailField(max_length=75, unique=True),
        ),
    ]
