
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-03-09T15:29:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fdb0c54b6e93f0e6e5cb64012543431d15a513a",
 "version": "0.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
