# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-18 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import mailqueue.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0006_auto_20190815_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=mailqueue.utils.upload_to),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
    ]
