# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WalletParameters(Model):
    """WalletParameters.

    :param owner_name:
    :type owner_name: str
    """

    _attribute_map = {
        'owner_name': {'key': 'ownerName', 'type': 'str'},
    }

    def __init__(self, *, owner_name: str=None, **kwargs) -> None:
        super(WalletParameters, self).__init__(**kwargs)
        self.owner_name = owner_name
