# Generated by Django 2.2.2 on 2019-08-08 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0064_auto_20190808_0401")]

    operations = [
        migrations.AlterField(
            model_name="historicalmedicalexpenses",
            name="duration_present_condition",
            field=models.IntegerField(
                help_text="in days",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="How long have you been sick with your current condition?",
            ),
        ),
        migrations.AlterField(
            model_name="medicalexpenses",
            name="duration_present_condition",
            field=models.IntegerField(
                help_text="in days",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="How long have you been sick with your current condition?",
            ),
        ),
    ]
