# Generated by Django 2.2.2 on 2019-08-21 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0067_auto_20190821_1538")]

    operations = [
        migrations.AlterField(
            model_name="bloodresult",
            name="cd4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="abs CD4",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbloodresult",
            name="cd4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="abs CD4",
            ),
        ),
    ]
