# Generated by Django 2.2 on 2019-05-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ambition_subject", "0050_auto_20190521_1818")]

    operations = [
        migrations.RenameField(
            model_name="historicalpatienthistory",
            old_name="tablets_missed",
            new_name="current_arv_tablets_missed",
        ),
        migrations.RenameField(
            model_name="historicalpatienthistory",
            old_name="arv_date",
            new_name="initial_arv_date",
        ),
        migrations.RenameField(
            model_name="historicalpatienthistory",
            old_name="arv_date_estimated",
            new_name="initial_arv_date_estimated",
        ),
        migrations.RenameField(
            model_name="patienthistory",
            old_name="tablets_missed",
            new_name="current_arv_tablets_missed",
        ),
        migrations.RenameField(
            model_name="patienthistory",
            old_name="arv_date",
            new_name="initial_arv_date",
        ),
        migrations.RenameField(
            model_name="patienthistory",
            old_name="arv_date_estimated",
            new_name="initial_arv_date_estimated",
        ),
    ]
