# Generated by Django 2.2.9 on 2020-03-02 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambition_subject", "0071_auto_20191201_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmedicalexpensestwodetail",
            name="transport_duration",
            field=models.CharField(
                blank=True,
                help_text="Specify as hours:minutes (format HH:MM)",
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9]{1,3}:[0-5][0-9])$",
                        message="Enter a valid time in hour:minutes format",
                    )
                ],
                verbose_name="How long did it take you to reach there?",
            ),
        ),
        migrations.AlterField(
            model_name="medicalexpensestwodetail",
            name="transport_duration",
            field=models.CharField(
                blank=True,
                help_text="Specify as hours:minutes (format HH:MM)",
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9]{1,3}:[0-5][0-9])$",
                        message="Enter a valid time in hour:minutes format",
                    )
                ],
                verbose_name="How long did it take you to reach there?",
            ),
        ),
    ]
