BACTERIA = "bacteria"
CRYPTOCOCCUS_NEOFORMANS = "cryptococcus_neoformans"
HEADACHE = "headache"
KLEBSIELLA_SPP = "klebsiella_sp"
NO_GROWTH = "no_growth"
VISUAL_LOSS = "visual_loss"
WORKING = "working"
