
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5bdf8fcee8c4e2104e320b3aaa9dd65c936673fb",
 "version": "2267"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
