# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Haid(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"ha_uuid": "str"}

    attribute_map = {"ha_uuid": "ha_uuid"}

    def __init__(self, ha_uuid=None):  # noqa: E501
        """Haid - a model defined in OpenAPI"""  # noqa: E501

        self._ha_uuid = None
        self.discriminator = None

        if ha_uuid is not None:
            self.ha_uuid = ha_uuid

    @property
    def ha_uuid(self):
        """Gets the ha_uuid of this Haid.  # noqa: E501


        :return: The ha_uuid of this Haid.  # noqa: E501
        :rtype: str
        """
        return self._ha_uuid

    @ha_uuid.setter
    def ha_uuid(self, ha_uuid):
        """Sets the ha_uuid of this Haid.


        :param ha_uuid: The ha_uuid of this Haid.  # noqa: E501
        :type: str
        """

        self._ha_uuid = ha_uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Haid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
