# Generated by Django 2.2.6 on 2019-10-16 23:07

import _socket
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_action_item.managers
import edc_model.validators.date
import edc_protocol.validators
import edc_utils.date
import edc_model_fields.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [("ambition_ae", "0040_auto_20191017_0107")]

    operations = [
        migrations.AlterModelOptions(
            name="antibiotictreatment",
            options={"ordering": ["display_index", "display_name"]},
        ),
        migrations.AlterModelOptions(
            name="meningitissymptom",
            options={"ordering": ["display_index", "display_name"]},
        ),
        migrations.AlterModelOptions(
            name="neurological",
            options={"ordering": ["display_index", "display_name"]},
        ),
        migrations.RemoveIndex(
            model_name="antibiotictreatment", name="ambition_ae_id_ad1f15_idx",
        ),
        migrations.RemoveIndex(
            model_name="meningitissymptom", name="ambition_ae_id_5c9519_idx",
        ),
        migrations.RemoveIndex(
            model_name="neurological", name="ambition_ae_id_658177_idx",
        ),
        migrations.RenameField(
            model_name="antibiotictreatment", old_name="name", new_name="display_name",
        ),
        migrations.RenameField(
            model_name="meningitissymptom", old_name="name", new_name="display_name",
        ),
        migrations.RenameField(
            model_name="neurological", old_name="name", new_name="display_name",
        ),
        migrations.RenameField(
            model_name="antibiotictreatment", old_name="short_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="meningitissymptom", old_name="short_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="neurological", old_name="short_name", new_name="name",
        ),
        migrations.AlterField(
            model_name="aefollowup",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.Site",
            ),
        ),
        migrations.AlterField(
            model_name="aeinitial",
            name="ae_classification_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="aeinitial",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.Site",
            ),
        ),
        migrations.AlterField(
            model_name="aesusar",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.Site",
            ),
        ),
        migrations.AlterField(
            model_name="aetmg",
            name="ae_classification_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="aetmg",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.Site",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="ae_classification_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaetmg",
            name="ae_classification_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="recurrencesymptom",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.Site",
            ),
        ),
        migrations.AddIndex(
            model_name="antibiotictreatment",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_ae_id_7e34e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meningitissymptom",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_ae_id_dede12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="neurological",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="ambition_ae_id_bc3c20_idx",
            ),
        ),
    ]
