
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-17T17:16:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c3b4a90e7276dc5c52d2025a262e01d2574fb55",
 "version": "1.3.3.post.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
