
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-13T13:44:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0f2ffd84857f1348d60a1e63174e42bcd874c73",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
