#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pybrock']

package_data = \
{'': ['*']}

install_requires = \
['pandas', 'pantab', 'us', 'requests']

setup(name='pybrock',
      version='0.13',
      description='A library to organize snippets and helpers that I find useful. ',
      author='Brock Tibert',
      author_email='btibert3@gmail.com',
      url='https://github.com/Btibert3/brock-python',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
