
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-09T17:02:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e12bdf3898c6dbc52d6869ff482d4921e784cc39",
 "version": "v2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
