# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcapi/file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpcapi/file.proto',
  package='file',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12grpcapi/file.proto\x12\x04\x66ile\"$\n\x04\x42\x65\x61t\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\"\x1e\n\x0c\x42\x65\x61tResponse\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\"\x1e\n\x0eGetFileRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\" \n\x0fGetFileResponse\x12\r\n\x05is_ok\x18\x01 \x01(\x08\x32v\n\x0bIFileClient\x12-\n\tHeartBeat\x12\n.file.Beat\x1a\x12.file.BeatResponse\"\x00\x12\x38\n\x07GetFile\x12\x14.file.GetFileRequest\x1a\x15.file.GetFileResponse\"\x00\x62\x06proto3')
)




_BEAT = _descriptor.Descriptor(
  name='Beat',
  full_name='file.Beat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='file.Beat.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='file.Beat.hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=64,
)


_BEATRESPONSE = _descriptor.Descriptor(
  name='BeatResponse',
  full_name='file.BeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='file.BeatResponse.active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=96,
)


_GETFILEREQUEST = _descriptor.Descriptor(
  name='GetFileRequest',
  full_name='file.GetFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='file.GetFileRequest.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=128,
)


_GETFILERESPONSE = _descriptor.Descriptor(
  name='GetFileResponse',
  full_name='file.GetFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_ok', full_name='file.GetFileResponse.is_ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['Beat'] = _BEAT
DESCRIPTOR.message_types_by_name['BeatResponse'] = _BEATRESPONSE
DESCRIPTOR.message_types_by_name['GetFileRequest'] = _GETFILEREQUEST
DESCRIPTOR.message_types_by_name['GetFileResponse'] = _GETFILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Beat = _reflection.GeneratedProtocolMessageType('Beat', (_message.Message,), {
  'DESCRIPTOR' : _BEAT,
  '__module__' : 'grpcapi.file_pb2'
  # @@protoc_insertion_point(class_scope:file.Beat)
  })
_sym_db.RegisterMessage(Beat)

BeatResponse = _reflection.GeneratedProtocolMessageType('BeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _BEATRESPONSE,
  '__module__' : 'grpcapi.file_pb2'
  # @@protoc_insertion_point(class_scope:file.BeatResponse)
  })
_sym_db.RegisterMessage(BeatResponse)

GetFileRequest = _reflection.GeneratedProtocolMessageType('GetFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFILEREQUEST,
  '__module__' : 'grpcapi.file_pb2'
  # @@protoc_insertion_point(class_scope:file.GetFileRequest)
  })
_sym_db.RegisterMessage(GetFileRequest)

GetFileResponse = _reflection.GeneratedProtocolMessageType('GetFileResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFILERESPONSE,
  '__module__' : 'grpcapi.file_pb2'
  # @@protoc_insertion_point(class_scope:file.GetFileResponse)
  })
_sym_db.RegisterMessage(GetFileResponse)



_IFILECLIENT = _descriptor.ServiceDescriptor(
  name='IFileClient',
  full_name='file.IFileClient',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=164,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='file.IFileClient.HeartBeat',
    index=0,
    containing_service=None,
    input_type=_BEAT,
    output_type=_BEATRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFile',
    full_name='file.IFileClient.GetFile',
    index=1,
    containing_service=None,
    input_type=_GETFILEREQUEST,
    output_type=_GETFILERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IFILECLIENT)

DESCRIPTOR.services_by_name['IFileClient'] = _IFILECLIENT

# @@protoc_insertion_point(module_scope)
