#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['hashable_ndframes']

package_data = \
{'': ['*']}

install_requires = \
['pandas >= 0.25']

setup(name='hashable_ndframes',
      version='0.1.3',
      description='Hashable (pandas) Series and DataFrames.',
      author='Bao Wei',
      author_email='baowei.ur521@gmail.com',
      url='https://github.com/baowei521/hashable_ndframes',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
