#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['excimer_referencer']

package_data = \
{'': ['*']}

install_requires = \
['pandas', 'scikit-image', 'numpy', 'affine', 'GDAL', 'fire']

entry_points = \
{'console_scripts': ['referencer = excimer_referencer.referencer:cli_helper']}

setup(name='excimer_referencer',
      version='0.5',
      description='A package to reference .jpeg, .bmp. and .png images using .xml metadata produced by an Excimer laser ablation system.',
      author='Ryan Avery',
      author_email='ravery@ucsb.edu',
      url='https://github.com/rbavery/excimer_referencer',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
